server:
  port: 8080
mpesa:
  daraja:
    consumer-key: JxCzrJQwCW5bWBrFCG5Y7IUx3xN827Pq
    consumer-secret: ab9PQt3uVP1tCzrW
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
#    shortCode: 600997
    shortCode: 603021
    confirmationURL: https://d8ff-105-163-1-230.ngrok-free.app/mobile-money/confirmation
    validationURL: https://d8ff-105-163-1-230.ngrok-free.app/mobile-money/validation
    responseType: Completed
#    b2c-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
#    b2c-result-url: https://279eba87a32e.ngrok.io/mobile-money/transaction-result
#    b2c-queue-timeout-url: https://279eba87a32e.ngrok.io/mobile-money/b2c-queue-timeout
#    b2c-initiator-name: apiop37
#    b2c-initiator-password: Safaricom3021#
#    transactionResultUrl: https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query
#    checkAccountBalanceUrl: https://sandbox.safaricom.co.ke/mpesa/accountbalance/v1/query
#    stkPassKey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
#    stkPushShortCode: 174379
#    stkPushRequestUrl: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
#    stkPushRequestCallbackUrl: https://279eba87a32e.ngrok.io/mobile-money/stk-transaction-result
#    lnmQueryRequestUrl: https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query